export const ORDER_COPY = {
  doorTitle: "Dispensary Login",
  doorLine: "Licensed New York dispensary access. A new account stays pending until Bond operations elevates it.",
  email: "Account email",
  license: "NY OCM license number",
  password: "Create password",
  confirm: "Confirm password",
  returnPassword: "Password",
  age21: "For adults 21 and over.",
  createAccess: "Create access",
  enter: "Enter",
  returnDoor: "Return to this door",
  createDoor: "Create access instead",
  close: "Close",
  mainPage: "Main page",
  privacy: "Privacy",
  formTitle: "Order reservation",
  formLine: "Reservation files as a Bond Orders draft. No Metrc write.",
  licenseCheck: "License check against Bond account record.",
  pendingBlock: "This account is pending. Bond operations must elevate it before a reservation can be filed.",
  qty: "Quantity",
  shipWeek: "Requested ship week",
  notes: "Notes",
  notesHint: "Receiving or delivery notes. Do not include SSN, date of birth, payment cards, or government ID.",
  review: "Review",
  back: "Back",
  submit: "Submit reservation",
  filed: "Reservation filed as a Bond Orders draft.",
  emptyLines: "Add a quantity for at least one SKU.",
  blockedSubmit: "This account cannot file a reservation.",
  matchFail: "Password and confirmation do not match.",
} as const;

export const PARTNER_SKU_LABELS = {
  "no-1": "No. 1 Dialed",
  "no-2": "No. 2 Unwind",
  "no-3": "No. 3 Peak",
} as const;
